# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.6
  - 3.5
  - 3.4
  - 2.7

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U tox-travis

# Command to run tests, e.g. python setup.py test
script: tox

{% if cookiecutter.use_pypi_deployment_with_travis == 'y' -%}
# Use travis-encrypt to encrypt the PyPI password for Travis:
# travis-encrypt {{ cookiecutter.github_username }} {{ cookiecutter.project_slug }}
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: {{ cookiecutter.pypi_username }}
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    condition: "$TRAVIS_TAG =~ ^[0-9]+.[0-9]+.[0-9]+$"
    repo: {{ cookiecutter.github_username }}/{{ cookiecutter.project_slug }}
    python: 3.6
{%- endif %}
